# Generated by Django 2.0.3 on 2018-03-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawldata',
            old_name='naem',
            new_name='name',
        ),
    ]
